# -*- coding: utf-8 -*-
"""src/app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlymQo4dwI3CWqXoh3ryAf5ESV8w9oc2
"""

#!/usr/bin/env python3

from flask import Flask, request

# Initialize the Flask application
app = Flask(__name__)

# Define the route for the main page ("/")
@app.route("/")
def main():
    """
    Renders a simple HTML form that allows the user to input text.
    When the form is submitted, it will send a POST request to '/echo_user_input'.
    """
    return '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Flask Input Echo</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
        <style>
            body {
                font-family: 'Inter', sans-serif;
                background-color: #f0f2f5;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                margin: 0;
            }
            .container {
                background-color: #ffffff;
                padding: 2.5rem;
                border-radius: 1rem;
                box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
                text-align: center;
                width: 100%;
                max-width: 28rem;
            }
            input[type="text"] {
                width: calc(100% - 2rem);
                padding: 0.75rem;
                margin-bottom: 1rem;
                border: 1px solid #d1d5db;
                border-radius: 0.5rem;
                font-size: 1rem;
                outline: none;
                transition: border-color 0.2s;
            }
            input[type="text"]:focus {
                border-color: #3b82f6; /* Tailwind blue-500 */
            }
            input[type="submit"] {
                background-color: #3b82f6; /* Tailwind blue-500 */
                color: white;
                padding: 0.75rem 1.5rem;
                border: none;
                border-radius: 0.5rem;
                font-size: 1rem;
                font-weight: 500;
                cursor: pointer;
                transition: background-color 0.2s ease-in-out;
            }
            input[type="submit"]:hover {
                background-color: #2563eb; /* Tailwind blue-600 */
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="text-2xl font-bold text-gray-800 mb-6">Enter Your Text</h1>
            <form action="/echo_user_input" method="POST">
                <input type="text" name="user_input" placeholder="Type something here..." class="shadow-sm">
                <input type="submit" value="Submit!" class="shadow-md">
            </form>
        </div>
    </body>
    </html>
    '''

# Define the route for processing user input, only accepting POST requests
@app.route("/echo_user_input", methods=["POST"])
def echo_input():
    """
    Receives the user input from the form, retrieves it, and displays it back to the user.
    Uses request.form.get() to safely retrieve the 'user_input' field, with an empty string
    as a default if not found.
    """
    input_text = request.form.get("user_input", "")
    return f'''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Your Input</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
        <style>
            body {{
                font-family: 'Inter', sans-serif;
                background-color: #f0f2f5;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                margin: 0;
            }}
            .container {{
                background-color: #ffffff;
                padding: 2.5rem;
                border-radius: 1rem;
                box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
                text-align: center;
                width: 100%;
                max-width: 28rem;
            }}
            .result-text {{
                font-size: 1.25rem;
                color: #1f2937; /* Tailwind gray-800 */
                margin-bottom: 1.5rem;
                word-wrap: break-word; /* Ensure long words wrap */
            }}
            .back-button {{
                background-color: #4f46e5; /* Tailwind indigo-600 */
                color: white;
                padding: 0.75rem 1.5rem;
                border: none;
                border-radius: 0.5rem;
                font-size: 1rem;
                font-weight: 500;
                cursor: pointer;
                transition: background-color 0.2s ease-in-out;
            }}
            .back-button:hover {{
                background-color: #4338ca; /* Tailwind indigo-700 */
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="text-2xl font-bold text-gray-800 mb-6">Your Input</h1>
            <p class="result-text">You entered: <strong class="text-blue-600">{input_text}</strong></p>
            <a href="/" class="back-button">Go Back</a>
        </div>
    </body>
    </html>
    '''

# This block ensures the Flask app runs only when the script is executed directly
if __name__ == "__main__":
    app.run(debug=True) # debug=True enables reloader and debugger